/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdlib.h> // for NULL
/* Header for class com_qd_gtcom_wangzhengcheng_ns_NsUtils */
#include "noise_suppression_x.h"
#include "noise_suppression.h"
#ifndef _Included_com_qd_gtcom_wangzhengcheng_ns_NsUtils
#define _Included_com_qd_gtcom_wangzhengcheng_ns_NsUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    create
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsCreate
        (JNIEnv *env, jobject obj){
    NsHandle* handle = NULL;
    WebRtcNs_Create(&handle);

    return (int)handle;
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    init
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsInit
        (JNIEnv *env, jobject obj, jint nsHandler, jint frequency){
    NsHandle *handler = (NsHandle *) nsHandler;
    if (handler == NULL){
        return -3;
    }
    return WebRtcNs_Init(handler,frequency);
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    setPolicy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsSetPolicy
        (JNIEnv *env, jobject obj, jint nsHandler, jint mode){

    NsHandle *handle = (NsHandle *) nsHandler;

    if (handle == NULL){
        return -3;
    }
    return WebRtcNs_set_policy(handle,mode);

}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    process
 * Signature: (I[SI[S)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsProcess
        (JNIEnv *env, jobject obj, jint nsHandler, jshortArray sample, jshortArray sample_H, jshortArray out,jshortArray out_H){
    NsHandle *handle = (NsHandle *) nsHandler;
    if(handle == NULL){
        return -3;
    }
    short* spframe = NULL;
    short* outframe = NULL;
    short* spframe_H = NULL;
    short* outframe_H = NULL;

    int ret = -1;
    spframe = (*env)->GetShortArrayElements(env,sample, NULL);
    outframe = (*env)->GetShortArrayElements(env,out, NULL);
    if(sample_H != NULL){
        spframe_H = (*env)->GetShortArrayElements(env,sample_H, NULL);
    }
    if(out_H != NULL){
        outframe_H = (*env)->GetShortArrayElements(env,out_H, NULL);
    }

    ret = WebRtcNs_Process(handle,spframe,spframe_H,outframe,outframe_H);

    (*env)->ReleaseShortArrayElements(env,sample, spframe, 0);
    (*env)->ReleaseShortArrayElements(env,out, outframe, 0);

    if(sample_H != NULL){
        (*env)->ReleaseShortArrayElements(env,sample_H, spframe_H, 0);
    }
    if(out_H != NULL){
        (*env)->ReleaseShortArrayElements(env,out_H, outframe_H, 0);
    }

    return ret;

}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    free
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsFree
         (JNIEnv *env, jobject obj, jint nsHandler){
    NsHandle *handle = (NsHandle *) nsHandler;
    if(handle == NULL){
        return -3;
    }

    return WebRtcNs_Free(handle);

}




                            /** NSX PROCESS*/



/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    nsxCreate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsxCreate
        (JNIEnv *env, jobject obj){

    NsHandle* handle = NULL;
    WebRtcNsx_Create(&handle);

    return (int)handle;

}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    nsxInit
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsxInit
        (JNIEnv *env, jobject obj, jint nsxHandler, jint frequency ){
    NsHandle *handler = (NsHandle *) nsxHandler;
    if (handler == NULL){
        return -3;
    }
    return WebRtcNsx_Init(handler,frequency);

}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    nsxSetPolicy
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsxSetPolicy
        (JNIEnv *env, jobject obj, jint nsxHandler, jint mode){
    NsHandle *handle = (NsHandle *) nsxHandler;

    if (handle == NULL){
        return -3;
    }
    return WebRtcNsx_set_policy(handle,mode);
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    nsxProcess
 * Signature: (I[SI[S)I
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsxProcess
        (JNIEnv *env, jobject obj, jint nsxHandler, jshortArray sample, jshortArray sample_H, jshortArray out,jshortArray out_H){
    NsHandle *handle = (NsHandle *) nsxHandler;
    if(handle == NULL){
        return -3;
    }
    short* spframe = NULL;
    short* outframe = NULL;
    short* spframe_H = NULL;
    short* outframe_H = NULL;

    int ret = -1;
    spframe = (*env)->GetShortArrayElements(env,sample, NULL);
    outframe = (*env)->GetShortArrayElements(env,out, NULL);
    if(sample_H != NULL){
        spframe_H = (*env)->GetShortArrayElements(env,sample_H, NULL);
    }
    if(out_H != NULL){
        outframe_H = (*env)->GetShortArrayElements(env,out_H, NULL);
    }

    ret = WebRtcNsx_Process(handle,spframe,spframe_H,outframe,outframe_H);

    (*env)->ReleaseShortArrayElements(env,sample, spframe, 0);
    (*env)->ReleaseShortArrayElements(env,out, outframe, 0);

    if(sample_H != NULL){
        (*env)->ReleaseShortArrayElements(env,sample_H, spframe_H, 0);
    }
    if(out_H != NULL){
        (*env)->ReleaseShortArrayElements(env,out_H, outframe_H, 0);
    }

    return ret;
}

/*
 * Class:     com_qd_gtcom_wangzhengcheng_ns_NsUtils
 * Method:    nsxFree
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_com_qd_gtcom_wangzhengcheng_ns_NsUtils_nsxFree
        (JNIEnv *env, jobject obj, jint nsxHandler){
    NsHandle *handle = (NsHandle *) nsxHandler;
    if(handle == NULL){
        return -3;
    }

    return WebRtcNsx_Free(handle);
}

#ifdef __cplusplus
}
#endif
#endif
